# Generated by Django 4.0.4 on 2022-05-31 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycharm', '0004_language_framework'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('movies', models.ManyToManyField(to='pycharm.movie')),
            ],
        ),
    ]
